### ISSUE TITLE
Update limit on RSS 

### ISSUE THREAD

**Issue by StevenDahFish** [soylent/offstream#2]
Is there a way that we can update the limit of amount of results shown in the RSS feed. As of right now, it only shows the latest 20 results  with the rest of the entries only accessible through the database.

**Comment by soylent** [comment]
Thanks for the question! Currently, the limit is hardcoded and set to 20, but I'll add a query param to fix this: `GET /rss?limit=100`.

**Comment by soylent** [comment]
Done. Please see v1.0.3.
